#!/usr/bin/env bash

set -euxo pipefail

SCRIPTS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
ROOT_DIR="$(dirname "${SCRIPTS_DIR}")"

if [ -f "${ROOT_DIR}/.env" ]; then
  set -a
  source "${ROOT_DIR}/.env"
  set +a
fi

npm run dev:server &
npm run dev:web &

wait
